mysql:
  host: "127.0.0.1"
  port: 3306
  db: gvb_db
  user: root
  password: root
  loglevel: dev

logger:
  level: info
  prefix: '[gvb]'
  director: log
  showline: true
  loginconsole: true


system:
  host: "0.0.0.0"
  port: 8080
  env: dev

